<!-- ImageReady Slices (Untitled-1) -->
<TABLE WIDTH=160 BORDER=0 CELLPADDING=0 CELLSPACING=0>
	<TR>
		<TD COLSPAN=7>
			<IMG SRC="/parsec_web/images/navigator_01.jpg" WIDTH=160 HEIGHT=16 ALT=""></TD>
	</TR>
	<TR>
		<TD ROWSPAN=6>
			<IMG SRC="/parsec_web/images/navigator_02.jpg" WIDTH=17 HEIGHT=144 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_03.jpg" WIDTH=39 HEIGHT=38 ALT=""></TD>
		<TD ROWSPAN=6>
			<IMG SRC="/parsec_web/images/navigator_04.jpg" WIDTH=6 HEIGHT=144 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_05.jpg" WIDTH=36 HEIGHT=38 ALT=""></TD>
		<TD COLSPAN=3 ROWSPAN=2>
			<IMG SRC="/parsec_web/images/navigator_06.jpg" WIDTH=62 HEIGHT=45 ALT=""></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_07.jpg" WIDTH=39 HEIGHT=7 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_08.jpg" WIDTH=36 HEIGHT=7 ALT=""></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_09.jpg" WIDTH=39 HEIGHT=37 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_10.jpg" WIDTH=36 HEIGHT=37 ALT=""></TD>
		<TD ROWSPAN=4>
			<IMG SRC="/parsec_web/images/navigator_11.jpg" WIDTH=8 HEIGHT=99 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_12.jpg" WIDTH=37 HEIGHT=37 ALT=""></TD>
		<TD ROWSPAN=4>
			<IMG SRC="/parsec_web/images/navigator_13.jpg" WIDTH=17 HEIGHT=99 ALT=""></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_14.jpg" WIDTH=39 HEIGHT=6 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_15.jpg" WIDTH=36 HEIGHT=6 ALT=""></TD>
		<TD ROWSPAN=3>
			<IMG SRC="/parsec_web/images/navigator_16.jpg" WIDTH=37 HEIGHT=62 ALT=""></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_17.jpg" WIDTH=39 HEIGHT=38 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_18.jpg" WIDTH=36 HEIGHT=38 ALT=""></TD>
	</TR>
	<TR>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_19.jpg" WIDTH=39 HEIGHT=18 ALT=""></TD>
		<TD>
			<IMG SRC="/parsec_web/images/navigator_20.jpg" WIDTH=36 HEIGHT=18 ALT=""></TD>
	</TR>
</TABLE>
<!-- End ImageReady Slices -->
